config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  devise_for :members, skip: [:passwords], controllers: {
    sessions:      'public/sessions',
    registrations: 'public/registrations'
  }

  devise_scope :member do
      post  'guests/sign_in' => 'public/sessions#new_guest', as: 'guest'
    end

  scope module: :public do
      root to: 'homes#top'

      get   'members/mypage'           => 'members#mypage',      as: 'mypage'
      get   'members/information/edit' => 'members#edit',        as: 'edit_information'
      get   'members/unsubscribe'      => 'members#unsubscribe', as: 'unsubscribe'
      patch 'members/withdraw'         => 'members#withdraw',    as: 'withdraw_member'
      patch 'members/information'      => 'members#update',      as: 'update_information'
      get   'post/hashtag/:name'       => 'posts#hashtag',       as: 'hashtag'
      get   '/search'                  => 'searches#search',     as: 'search'

      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resources :comments,  only: [:create, :destroy]
      end

      resources :members,    only: [:index, :show]
      resources :categories, only: [:index]
    end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
    }

  namespace :admin do
      get 'top' => 'homes#top', as: 'top'
      get 'hashtag/:name' => 'posts#hashtag', as: 'hashtag'

      resources :posts,       only: [:index, :show, :destroy]
      resources :members,     only: [:index, :show, :edit, :update]
      resources :comments,    only: [:index, :show, :destroy]
      resources :categories,  only: [:index, :create, :edit, :update]
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :post



  validates :body, presence: true

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
     @comments = Comment.all.page(params[:page]).per(10)
  end

  def destroy
       @comment = Comment.find(params[:id])
       if @comment.destroy
          redirect_back(fallback_location: root_path)
       else
          redirect_back(fallback_location: root_path)
       end
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_index.html.erb
<table class = "table">
  <tr class="table-info">
    <th>内容</th>
    <th>投稿者</th>
  </tr>
  <tr class="table-info">
    <% comment.each do |comment| %>
    <td><%= link_to comment.body, admin_post_path(comment.post) %></td>
    <td><%= link_to comment.member.nick_name, admin_member_path(comment.member_id) %></td>
  </tr>
    <% end %>
    <%= paginate comment %>
</table>

app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/comments/index.html.erb
 <br>
 <div class='row justify-content-center'>
    <h4 class="section-ttl font-weight-bold">コメント一覧</h4>
  </div>
  <div class='row justify-content-center'>
    <div class='col-5'>
      <%= render 'admin/comments/index', comment: @comments %>
    </div>
  </div>