config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  devise_for :members, skip: [:passwords], controllers: {
    sessions:      'public/sessions',
    registrations: 'public/registrations'
  }

  devise_scope :member do
      post  'guests/sign_in' => 'public/sessions#new_guest', as: 'guest'
    end

  scope module: :public do
      root to: 'homes#top'

      get   'members/mypage'           => 'members#mypage',      as: 'mypage'
      get   'members/information/edit' => 'members#edit',        as: 'edit_information'
      get   'members/unsubscribe'      => 'members#unsubscribe', as: 'unsubscribe'
      patch 'members/withdraw'         => 'members#withdraw',    as: 'withdraw_member'
      patch 'members/information'      => 'members#update',      as: 'update_information'
      get   'post/hashtag/:name'       => 'posts#hashtag',       as: 'hashtag'
      get   '/search'                  => 'searches#search',     as: 'search'

      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resources :comments,  only: [:create, :destroy]
      end

      resources :members,    only: [:index, :show]
      resources :categories, only: [:index]
    end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
    }

  namespace :admin do
      get 'top' => 'homes#top', as: 'top'
      get 'hashtag/:name' => 'posts#hashtag', as: 'hashtag'

      resources :posts,       only: [:index, :show, :destroy]
      resources :members,     only: [:index, :show, :edit, :update]
      resources :comments,    only: [:index, :show, :destroy]
      resources :categories,  only: [:index, :create, :edit, :update]
    end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :introduction, length: { maximum: 200 }
  validates :name, presence: true
  validates :nick_name, presence: true

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  scope :only_active, -> { where(is_deleted: true) }

def self.guest
  find_or_create_by!(email: 'guest@guest.com') do |member|
    member.password = SecureRandom.urlsafe_base64
    member.name = 'ゲスト'
    member.nick_name = 'ゲストユーザー'
  end
end

#ログイン時に退会済みのユーザーが同じアカウントでログインできないように制約
def active_for_authentication?
    super && (self.is_deleted == false)   #is_deletedがtrueならfalseを返すようにしている
end

#アカウント編集時、現在のパスワードは不要だが、パスワードの変更を可能にする
def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
end

# ユーザー検索機能
def self.search_for(keyword,method)
    if method == "perfect"
      Member.where(["nick_name like?", "#{keyword}"])
    elsif method == "forward"
      Member.where(["nick_name like?", "#{keyword}%"])
    elsif method == "backward"
      Member.where(["nick_name like?", "%#{keyword}"])
    else
      Member.where(["nick_name like?", "%#{keyword}%"])
    end
 end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @members = Member.all.page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
       redirect_to admin_members_path
    else
      render 'edit'
    end
  end

    private

  def member_params
    params.require(:member).permit(:name, :nick_name, :ntroduction, :email, :is_deleted)
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/edit.html.erb
<div class='container'>
  <div class'row'>
    <h3 class="font-weight-bold"><%= @member.nick_name %>さんのユーザー情報編集</h3>

    <%= form_with model: @member,url: admin_member_path, method: "patch" do |f| %>
    <div class='col-md-9 mx-auto'>
      <table class='table table-borderless'>
        <tbody>

          <tr>
            <td>ユーザーID</td>
            <td><%= @member.id %></td>
          </tr>
          <tr>
            <td>名前</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td>表示名</td>
            <td><%= f.text_field :nick_name %></td>
          </tr>
    　　　　　<tr>
            <td>メールアドレス</td>
            <td><%= f.email_field :email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <%= f.radio_button :is_deleted, false %>有効
              <%= f.radio_button :is_deleted, true %>退会
            </td>
          </tr>

        </tbody>
      </table>

        <div class="form-group d-grid gap-1 col-5 mx-auto">
          <%= f.submit '保存を変更', class: 'btn btn-success btn-sm' %>
        </div>
     <% end %>
    </div>
  </div>
</div>

app/views/admin/members/index.html.erb
<div class='container'>
  <div class'row'>
     <h4 class="section-ttl font-weight-bold">ユーザー一覧</h4>
      <br>

      <div class='col-md-9 mx-auto'>
      <table class='table'>
        <thead>
          <tr class="table-secondary">
            <th>ユーザーID</th>
            <th>名前</th>
            <th>表示名</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @members.each do |member| %>
          <tr class="table-secondary">
            <td><%= member.id %></td>
            <td>
              <%= link_to admin_member_path(member.id) do %>
              <%= member.name %>
              <% end %>
            </td>
            <td><%= member.nick_name %></td>
            <td>
              <% if member.is_deleted %>
                <div class="text-danger font-weight-bold">退会</div>
              <% else %>
                <div class="text-success font-weight-bold">有効</div>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>

  </div>
    <div class= "text-center"><%= paginate @members %></div>
</div>

app/views/admin/members/show.html.erb
<div class="container">
  <h3><%= @member.nick_name %>さんの詳細</h3>
</div>
<br>
<div class="row justify-content-center">
  <div class="col-5">
    <table class="table">
      <tr>
        <th>ユーザーID</th>
        <td><%= @member.id %></td>
      </tr>
      <tr>
        <th>名前</th>
        <td><%= @member.name %></td>
      </tr>
      <tr>
        <th>表示名</th>
        <td><%= @member.nick_name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @member.email %></td>
      </tr>
      <tr>
        <th>ユーザーステータス</th>
        <td>
          <% if @member.is_deleted == false %>
            <div class="text-success font-weight-bold">有効</div>
          <% else %>
            <div class="text-danger font-weight-bold">退会</div>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>
 <div class="row justify-content-center">
          <%= link_to "編集する",edit_admin_member_path,class: "btn btn-success btn-sm" %>
      </div>

app/views/admin/members/update.html.erb
<h1>Admin::Members#update</h1>
<p>Find me in app/views/admin/members/update.html.erb</p>