config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  devise_for :members, skip: [:passwords], controllers: {
    sessions:      'public/sessions',
    registrations: 'public/registrations'
  }

  devise_scope :member do
      post  'guests/sign_in' => 'public/sessions#new_guest', as: 'guest'
    end

  scope module: :public do
      root to: 'homes#top'

      get   'members/mypage'           => 'members#mypage',      as: 'mypage'
      get   'members/information/edit' => 'members#edit',        as: 'edit_information'
      get   'members/unsubscribe'      => 'members#unsubscribe', as: 'unsubscribe'
      patch 'members/withdraw'         => 'members#withdraw',    as: 'withdraw_member'
      patch 'members/information'      => 'members#update',      as: 'update_information'
      get   'post/hashtag/:name'       => 'posts#hashtag',       as: 'hashtag'
      get   '/search'                  => 'searches#search',     as: 'search'

      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resources :comments,  only: [:create, :destroy]
      end

      resources :members,    only: [:index, :show]
      resources :categories, only: [:index]
    end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
    }

  namespace :admin do
      get 'top' => 'homes#top', as: 'top'
      get 'hashtag/:name' => 'posts#hashtag', as: 'hashtag'

      resources :posts,       only: [:index, :show, :destroy]
      resources :members,     only: [:index, :show, :edit, :update]
      resources :comments,    only: [:index, :show, :destroy]
      resources :categories,  only: [:index, :create, :edit, :update]
    end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
  belongs_to :category
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_hashtag_relations, dependent: :destroy
  has_many :hashtags, through: :post_hashtag_relations

  has_many_attached :image

  validates :title, presence: true
  validates :body, presence: true

  enum status: { draft:0, publish:1 }

# ブックマーク（いいね）機能
  #ユーザーidがfavoriteテーブル内に存在するかどうかを判別
  def favorited_by?(member)
      favorites.where(member_id: member.id).exists?
  end

# ハッシュタグ機能
  #DBへのコミット直前に実施する
  after_create do
    post = Post.find_by(id: self.id)
    hashtags  = self.caption.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    post.hashtags = []
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(hashname: hashtag.delete('#'))
      post.hashtags << tag
    end
  end

  before_update do
    post = Post.find_by(id: self.id)
    post.hashtags.clear
    hashtags = self.caption.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.delete('#'))
      post.hashtags << tag
    end
  end

 # キーワード検索機能
 def self.search_for(keyword,method)
    if method == "perfect"
      Post.where(["title like? OR body like?", "#{keyword}", "#{keyword}"])
    elsif method == "forward"
      Post.where(["title like? OR body like?", "#{keyword}%", "#{keyword}%"])
    elsif method == "backward"
      Post.where(["title like? OR body like?", "%#{keyword}", "%#{keyword}"])
    else
      Post.where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
    end
 end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
      @categories = Category.all
      if params[:category_id]                                   # urlにcategory_id(params)がある場合
          @category = @categories.find(params[:category_id])    # Categoryのデータベースのテーブルから一致するidを取得
          all_posts = @category.posts                           # category_idと紐づく投稿を取得
      else
          all_posts = Post.includes(:category)                  # 投稿すべてを取得
      end
      @posts = all_posts.page(params[:page]).per(10)
      @all_posts_count = all_posts.count
  end

  def show
      @post = Post.find(params[:id])
      @comments = @post.comments                  #投稿詳細に関連付けてあるコメントを全取得
      @comment_all = @comments.count
      @category = @post.category
  end

  def destroy
     @post = Post.find(params[:id])
     @post.destroy
     redirect_to admin_top_path
  end

  def hashtag
      @tag = Hashtag.find_by(hashname: params[:name])
      @posts = @tag.posts.page(params[:page]).per(10)
  end

   private

    def post_params
      params.require(:post).permit(:title, :body, {image:[]}, :status, :member_id, :category_id)
    end


end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
   def render_with_hashtag(caption)
    caption.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/admin/hashtag/#{word.delete("#")}"}.html_safe
   end
end

app/views/admin/posts/_index.html.erb
<table class = "table">
    <tr class="table-warning">
      <th></th>
      <th>タイトル</th>
      <th>内容</th>
      <th>投稿者</th>
      <th>公開ステータス</th>
    </tr>
    <% post.each do |post| %>
    <tr class="table-warning">
      <td class="image">
        <%= link_to admin_post_path(post) do %>
          <% if post.image.attached? %>
            <% post.image.first(1).each do |image| %> 　　<!--fisrt(1)で初めの一枚のみ表示-->
              <%= image_tag image, size:'80x50' %>
            <% end %>
          <% else %>
            <%= image_tag "/no-image.png", size:'80x50' %>
          <% end %>
      </td>
      <td><%= link_to post.title, admin_post_path(post) %></td>
        <% end %>
      <td><%= post.body.truncate(30) %></td>
      <td><%= post.member.nick_name %></td>
      <td><%= post.status_i18n %></td>
    </tr>
    <% end %>
    <%= paginate post %>
</table>

app/views/admin/posts/destroy.html.erb
<h1>Admin::Posts#destroy</h1>
<p>Find me in app/views/admin/posts/destroy.html.erb</p>

app/views/admin/posts/hashtag.html.erb
<div class="container">

    <div class="row justify-content-center">
     <div class='col-10'>
       <br>
       <h3 class="section-ttl font-weight-bold">#<%= @tag.hashname %></h3>
        <%= render 'admin/posts/index', post: @posts %>
     </div>
    </div>

</div>

app/views/admin/posts/idex.html.erb
<h1>Admin::Posts#idex</h1>
<p>Find me in app/views/admin/posts/idex.html.erb</p>

app/views/admin/posts/index.html.erb
<!--管理者/記事一覧-->
<div class="container">
  <div class="row justify-content-center">
    <div class='col-10'>
         <% if params[:category_id] %>
            <h3 class="section-ttl font-weight-bold"><%= @category.name %>の投稿一覧</h3>
            <h4 class="section-ttl">(全<%= @all_posts_count %>件)</h4>
　　　　 <% else %>
　　　　 <br>
      			<h3 class="section-ttl font-weight-bold">投稿一覧</h3>
      			<h4 class="section-ttl">(全<%= @all_posts_count %>件)</h4>
    		 <% end %>

		 <!--投稿一覧-->
        <% if @posts.first %>
           <%= render 'admin/posts/index', post: @posts %>
        <% else %>
 		   <h4>対応する投稿はありませんでした。</h4>
		<% end %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="admin-post-show">
    <br>
    <div class="col-8">
      <h4 class="section-ttl font-weight-bold"><%= @post.title %></h4>
      <li class="time"><%= @post.created_at.strftime("%Y/%m/%d %H:%M") %></li>
      <li class="cat">
        エリア：
          <%= link_to admin_posts_path(category_id: @category.id) do %>
          <%= @category.name %>
          <% end %>
      </li>
    </div>
    <hr class="hr3">
    <div class="col-8">
      <%= simple_format(@post.body) %><!--ヘルパーメソッド"simple_format"でフォームの改行反映-->
    </div>
    <div class="row justify-content-center">
      <% if @post.image.attached? %>
        <% @post.image.each do |image| %>
        <%= image_tag image, width: '50%' %>
        <% end %>
      <% end %>
    </div>
    <br>
    <br>
    <div class="col-12">
      <div class="tag"><%= render_with_hashtag(@post.caption) %></div> <!--リンク付きハッシュタグ-->
    </div>
    <br>
    <li class="delete-btn">
          <%= link_to "削除",  admin_post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger btn-sm" %>
    </li>

  <hr class="hr3">
    <br>
<div class="col-8">
    <h6 class="font-weight-bold">コメント(<%= @comments.count %>)</h6>
</div>

       <div class='col-8'>
         <div class='comment'>
      <% @comments.each do |comment| %>
        <hr class="hr2">
        <p><%= simple_format(comment.body) %></p>
        <li class="comment2">
          <i class="fa-regular fa-user"></i>
          <%= comment.member.nick_name %> |
          <%= comment.created_at.strftime("%Y/%m/%d %H:%M")  %>
        </li>
        <li class="comment-delete-btn">
           <%= link_to"削除", admin_comment_path(comment.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger btn-sm" %>
        </li>

      <% end %>
        <hr class="hr3">
       </div>
       </div>
</div>

</div>