config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  devise_for :members, skip: [:passwords], controllers: {
    sessions:      'public/sessions',
    registrations: 'public/registrations'
  }

  devise_scope :member do
      post  'guests/sign_in' => 'public/sessions#new_guest', as: 'guest'
    end

  scope module: :public do
      root to: 'homes#top'

      get   'members/mypage'           => 'members#mypage',      as: 'mypage'
      get   'members/information/edit' => 'members#edit',        as: 'edit_information'
      get   'members/unsubscribe'      => 'members#unsubscribe', as: 'unsubscribe'
      patch 'members/withdraw'         => 'members#withdraw',    as: 'withdraw_member'
      patch 'members/information'      => 'members#update',      as: 'update_information'
      get   'post/hashtag/:name'       => 'posts#hashtag',       as: 'hashtag'
      get   '/search'                  => 'searches#search',     as: 'search'

      resources :posts do
        resource :favorites, only: [:create, :destroy]
        resources :comments,  only: [:create, :destroy]
      end

      resources :members,    only: [:index, :show]
      resources :categories, only: [:index]
    end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions'
    }

  namespace :admin do
      get 'top' => 'homes#top', as: 'top'
      get 'hashtag/:name' => 'posts#hashtag', as: 'hashtag'

      resources :posts,       only: [:index, :show, :destroy]
      resources :members,     only: [:index, :show, :edit, :update]
      resources :comments,    only: [:index, :show, :destroy]
      resources :categories,  only: [:index, :create, :edit, :update]
    end

end

app/views/layouts/_category.html.erb
<!--切替ボタンの設定 -->
<div class="nav-link" id="dropdownMenuButton button_group" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <div class="btn btn-outline-dark font-weight-bold">エリア</div>
</div>
<!--ドロップメニューの設定 -->
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
  <% if admin_signed_in? %>
    <% category.each do |category| %>
      <%= link_to category.name,admin_posts_path(category_id: category.id), class: 'nav-link dropdown-item' %>
    <% end %>
  <% else %>
    <% category.each do |category| %>
      <%= link_to category.name, posts_path(category_id: category.id), class: 'nav-link dropdown-item' %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h3><%= t("errors.template.header", model: obj.model_name.human, count: obj.errors.count) %></h3>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-xl navbar-light" style="background-color: #ffd500;">
  <div class="navbar-brand" href="#">
    <%= link_to "旅ラフ", root_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %>
  </div>

 <% if admin_signed_in? %>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "管理者トップ", admin_top_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
        <li class="nav-item"><%= link_to "ユーザー一覧", admin_members_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
        <li class="nav-item"><%= link_to "投稿一覧", admin_posts_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
        <li class="nav-item"><%= link_to "コメント一覧", admin_comments_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
        <li class="nav-item dropdown">
          <div class="nav-item btn btn-outline-dark mx-2 font-weight-bold" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">エリア</div>
            <div class="dropdown-menu " aria-labelledby="navbarDropdown">
                <% @categories.each do |category| %>
                <%= link_to category.name,admin_posts_path(category_id: category.id), class: 'nav-link dropdown-item' %>
                <% end %>
            </div>
        </li>
        <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
        </ul>
  </div>

      <% elsif member_signed_in? %>
       <p class="welcome">ようこそ、<%= current_member.nick_name %>さん！</p>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">

               <li class="nav-item"><%= render 'public/searches/search' %></li>

                <li class="nav-item dropdown">
          <div class="nav-item btn btn-outline-dark mx-2 font-weight-bold" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">エリア</div>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% @categories.each do |category| %>
                <%= link_to category.name, posts_path(category_id: category.id), class: 'nav-link dropdown-item' %>
                <% end %>
            </div>
        </li>

              <li class="nav-item"><%= link_to '投稿一覧', posts_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
              <li class="nav-item"><%= link_to 'ユーザー一覧', members_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
              <li class="nav-item"><%= link_to 'マイページ', mypage_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
                <!--新規投稿-->
                <li class="nav-item dropdown">
                  <%= link_to new_post_path, class: "btn mx-2" do %>
                    <i class="fa-regular fa-square-plus fa-2x"></i>
                  <% end %>
                </li>
               <li class="nav-item"><%= render 'layouts/login' %></li>

              </ul>
            </div>

      <% else %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
              <li class="nav-item"><%= render 'public/searches/search' %></li>

              <li class="nav-item dropdown">
              <div class="nav-item btn btn-outline-dark mx-2 font-weight-bold" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">エリア</div>
              <div class="dropdown-menu " aria-labelledby="navbarDropdown">

                <% @categories.each do |category| %>
                <%= link_to category.name, posts_path(category_id: category.id), class: 'nav-link dropdown-item' %>
                <% end %>

              </div>
             </li>

              <li class="nav-item"><%= link_to '投稿一覧', posts_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
              <li class="nav-item"><%= link_to 'ユーザー一覧', members_path, class: "btn btn-outline-dark mx-2 font-weight-bold" %></li>
              <li class="nav-item"><%= render 'layouts/login' %></li>

  </ul>
  </div>
      <% end %>

</nav>

app/views/layouts/_login.html.erb
<li class="nav-item dropdown">
<!-- 切替ボタンの設定 -->
<div class="nav-link" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <i class="fa-regular fa-circle-user fa-2x"></i>
</div>
<!-- ドロップメニューの設定 -->
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
  <% if member_signed_in? %>
    <%= link_to 'アカウント編集', edit_member_registration_path, class: 'nav-link dropdown-item' %>
    <%= link_to 'ログアウト', destroy_member_session_path, method: :delete, class: 'nav-link dropdown-item' %>
  <% else %>
    <%= link_to "新規登録", new_member_registration_path, class: 'nav-link dropdown-item' %>
    <%= link_to "ログイン", new_member_session_path, class: 'nav-link dropdown-item' %>
    <%= link_to 'ゲストログイン（閲覧用）', guest_path, method: :post, class: 'nav-link dropdown-item' %>
  <% end %>
</div>
</li>

app/views/layouts/_search.html.erb
<!--検索フォーム-->
<%= form_with url: search_path, method: :get, local: true do |f| %>
  <%= f.text_field :keyword, :placeholder =>"投稿検索"  %>
  <%= f.select :method , options_for_select({"部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect" }) %>
  <%= f.submit '検索', class: "btn btn-dark btn-sm"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabiLaugh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- FontAwesomeのアイコンを使えるようにするURL-->
    <link href="https://use.fontawesome.com/releases/v6.2.0/css/all.css" rel="stylesheet">
    <!-- FontAwesomeのアイコンにアニメーションを付けられるURL-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
  </head>

  <body>
    <div class="container-app">
      <%= render 'layouts/header' %>
      <main>
        <%= yield %>
      </main>

      <footer class="<%= (admin_signed_in? ? "admin_footer" : "" ) %>"></footer>
    </div>
  </body>
</html>